version: '2'
services:
  mongodb:
    build: ./mongo
  backend:
    build: ./backend
    depends_on:
      - mongodb
    ports:
      - "4001:80"
  frontend:
    build: ./frontend
    depends_on:
      - backend
    ports:
      - "4002:443"
      - "8080:8080"
  webgl:
    build: ./webgl
    ports:
      - "4006:80"
